### ISSUE TITLE
Bad Object check in elementChildren function

### ISSUE THREAD

**Issue by Shai1436** [jeysal/pretty-format-snabbdom#2]
In `elementChildren` function the object check  ```typeof child === 'object' && child.text !== undefined``` is insufficient. It throws an error when the child is `null`.

**Comment by jeysal** [comment]
How can `child` be `null`?
`<div>{null}{undefined}</div>` has `children: [ { text: null }, { text: undefined } ]` where the text is `null`, but not the `child` itself.

**Comment by Shai1436** [comment]
I am not sure why it is `null` but in my case, the mounted vnode is this: ``` { sel: 'div',
        data:
         { hook: {},
           ref: { current: null },
           on: { scroll: [Function: onScroll] },
           style: { width: '627px' },
           class: {},
           attrs: {},
           props: { className: 'sn-gantt-grid-header' },
           dataset: {} },
        children:
         [ {
	      sel: 'div',
             data: [Object],
             children: [Array],
             text: undefined,
             elm: undefined,
             key: undefined 
            },
            null 
	],
        text: undefined,
        elm: undefined,
        key: undefined 
}```

**Comment by Shai1436** [comment]
This issue is coming because of conditional rendering: `showPopover ? <custom-popover/>: null`. If showPopover is `false` then null is returned to the view and when `pretty-format-snabbdom` parses this null object, it throws the error.

**Comment by jeysal** [comment]
I see, it can only occur when using `snabbdom` `h` directly. I first tried to add it in the `index.test` using `snabbdom-jsx`, which only created text nodes.
